var hierarchy =
[
    [ "UniformClient.Plugins.API", "d5/d12/class_uniform_client_1_1_plugins_1_1_a_p_i.html", null ],
    [ "UniformQueries.API", "df/d75/class_uniform_queries_1_1_a_p_i.html", null ],
    [ "WpfHandler.Plugins.API", "d2/d9a/class_wpf_handler_1_1_plugins_1_1_a_p_i.html", null ],
    [ "Application", null, [
      [ "TeacherHandbook.App", "d2/d56/class_teacher_handbook_1_1_app.html", null ],
      [ "TeacherHandbook.App", "d2/d56/class_teacher_handbook_1_1_app.html", null ],
      [ "TeacherHandbook.App", "d2/d56/class_teacher_handbook_1_1_app.html", null ],
      [ "TeacherHandbook.App", "d2/d56/class_teacher_handbook_1_1_app.html", null ],
      [ "TeacherHandbook.App", "d2/d56/class_teacher_handbook_1_1_app.html", null ]
    ] ],
    [ "ApplicationSettingsBase", null, [
      [ "TeacherHandbook.Properties.Settings", "d0/d4b/class_teacher_handbook_1_1_properties_1_1_settings.html", null ],
      [ "THB_Plugin_Exams.Properties.Settings", "dc/d5b/class_t_h_b___plugin___exams_1_1_properties_1_1_settings.html", null ],
      [ "THB_Plugin_Lesson.Properties.Settings", "d2/d6c/class_t_h_b___plugin___lesson_1_1_properties_1_1_settings.html", null ],
      [ "THB_Plugin_Orders.Properties.Settings", "dd/d9e/class_t_h_b___plugin___orders_1_1_properties_1_1_settings.html", null ],
      [ "THB_Plugin_Social.Properties.Settings", "d5/dbf/class_t_h_b___plugin___social_1_1_properties_1_1_settings.html", null ],
      [ "WpfHandler.Properties.Settings", "d7/d4f/class_wpf_handler_1_1_properties_1_1_settings.html", null ]
    ] ],
    [ "UniformClient.BaseClient", "d4/deb/class_uniform_client_1_1_base_client.html", [
      [ "TeacherHandbook.Client", "d8/de3/class_teacher_handbook_1_1_client.html", null ],
      [ "TestClient.Client", "d6/dac/class_test_client_1_1_client.html", null ],
      [ "UniformClient.SimpleClient", "d4/d3e/class_uniform_client_1_1_simple_client.html", null ]
    ] ],
    [ "UniformServer.BaseServer", "d7/d32/class_uniform_server_1_1_base_server.html", [
      [ "QueriesServer.Server", "d2/d9a/class_queries_server_1_1_server.html", null ],
      [ "SessionProvider.Server", "d8/d17/class_session_provider_1_1_server.html", null ],
      [ "THB_Data_Server.Server", "dc/d42/class_t_h_b___data___server_1_1_server.html", null ],
      [ "UniformServer.SimpleServer", "dc/d09/class_uniform_server_1_1_simple_server.html", null ]
    ] ],
    [ "PipesProvider.Client.ClientAPI", "d9/d01/class_pipes_provider_1_1_client_1_1_client_a_p_i.html", null ],
    [ "UniformServer.Commands", "d3/d12/class_uniform_server_1_1_commands.html", null ],
    [ "UniformClient.Plugins.Constants", "d2/d62/class_uniform_client_1_1_plugins_1_1_constants.html", null ],
    [ "PipesProvider.Security.Crypto", "d6/d06/class_pipes_provider_1_1_security_1_1_crypto.html", null ],
    [ "TeacherHandbook.Core.Containers.Schedule.Day", "d5/d0b/class_teacher_handbook_1_1_core_1_1_containers_1_1_schedule_1_1_day.html", null ],
    [ "PipesProvider.Handlers.DNS", "d4/d27/class_pipes_provider_1_1_handlers_1_1_d_n_s.html", null ],
    [ "TeacherHandbook.Client.DomainContainer", "db/de2/class_teacher_handbook_1_1_client_1_1_domain_container.html", null ],
    [ "PipesProvider.Security.General", "d6/d6b/class_pipes_provider_1_1_security_1_1_general.html", null ],
    [ "TeacherHandbook.Core.Containers.Entities.Group", "da/dfa/class_teacher_handbook_1_1_core_1_1_containers_1_1_entities_1_1_group.html", null ],
    [ "IComponentConnector", null, [
      [ "TeacherHandbook.CatalogButton", "d2/d3e/class_teacher_handbook_1_1_catalog_button.html", null ],
      [ "TeacherHandbook.Controls.CatalogButton", "df/d61/class_teacher_handbook_1_1_controls_1_1_catalog_button.html", null ],
      [ "TeacherHandbook.Controls.CatalogButton", "df/d61/class_teacher_handbook_1_1_controls_1_1_catalog_button.html", null ],
      [ "TeacherHandbook.Controls.CatalogButton", "df/d61/class_teacher_handbook_1_1_controls_1_1_catalog_button.html", null ],
      [ "TeacherHandbook.Controls.CatalogButton", "df/d61/class_teacher_handbook_1_1_controls_1_1_catalog_button.html", null ],
      [ "TeacherHandbook.Controls.UserControl1", "d6/dc1/class_teacher_handbook_1_1_controls_1_1_user_control1.html", null ],
      [ "TeacherHandbook.MainWindow", "df/d32/class_teacher_handbook_1_1_main_window.html", null ],
      [ "TeacherHandbook.MainWindow", "df/d32/class_teacher_handbook_1_1_main_window.html", null ],
      [ "TeacherHandbook.MainWindow", "df/d32/class_teacher_handbook_1_1_main_window.html", null ],
      [ "TeacherHandbook.MainWindow", "df/d32/class_teacher_handbook_1_1_main_window.html", null ],
      [ "TeacherHandbook.Plugins.Feed.Feed", "d2/d56/class_teacher_handbook_1_1_plugins_1_1_feed_1_1_feed.html", null ],
      [ "TeacherHandbook.Plugins.Feed.Feed", "d2/d56/class_teacher_handbook_1_1_plugins_1_1_feed_1_1_feed.html", null ],
      [ "TeacherHandbook.Plugins.Feed.Feed", "d2/d56/class_teacher_handbook_1_1_plugins_1_1_feed_1_1_feed.html", null ],
      [ "TeacherHandbook.Plugins.Feed.Feed", "d2/d56/class_teacher_handbook_1_1_plugins_1_1_feed_1_1_feed.html", null ],
      [ "TeacherHandbook.Plugins.Feed.Feed", "d2/d56/class_teacher_handbook_1_1_plugins_1_1_feed_1_1_feed.html", null ],
      [ "TeacherHandbook.Plugins.Feed.Feed", "d2/d56/class_teacher_handbook_1_1_plugins_1_1_feed_1_1_feed.html", null ],
      [ "TeacherHandbook.Plugins.Feed.Feed", "d2/d56/class_teacher_handbook_1_1_plugins_1_1_feed_1_1_feed.html", null ],
      [ "TeacherHandbook.Plugins.Schedule.Schedule", "dc/d1d/class_teacher_handbook_1_1_plugins_1_1_schedule_1_1_schedule.html", null ],
      [ "TeacherHandbook.Plugins.Schedule.Schedule", "dc/d1d/class_teacher_handbook_1_1_plugins_1_1_schedule_1_1_schedule.html", null ],
      [ "TeacherHandbook.Plugins.Schedule.Schedule", "dc/d1d/class_teacher_handbook_1_1_plugins_1_1_schedule_1_1_schedule.html", null ],
      [ "TeacherHandbook.Plugins.Schedule.Schedule", "dc/d1d/class_teacher_handbook_1_1_plugins_1_1_schedule_1_1_schedule.html", null ],
      [ "TeacherHandbook.Plugins.Schedule.Schedule", "dc/d1d/class_teacher_handbook_1_1_plugins_1_1_schedule_1_1_schedule.html", null ],
      [ "THB_Plugin_Exams.ExamPlanner", "df/df8/class_t_h_b___plugin___exams_1_1_exam_planner.html", null ],
      [ "THB_Plugin_Exams.ExamPlanner", "df/df8/class_t_h_b___plugin___exams_1_1_exam_planner.html", null ],
      [ "THB_Plugin_Exams.ExamPlanner", "df/df8/class_t_h_b___plugin___exams_1_1_exam_planner.html", null ],
      [ "THB_Plugin_Exams.ExamPlanner", "df/df8/class_t_h_b___plugin___exams_1_1_exam_planner.html", null ],
      [ "THB_Plugin_Exams.Monitor", "d9/d79/class_t_h_b___plugin___exams_1_1_monitor.html", null ],
      [ "THB_Plugin_Exams.Monitor", "d9/d79/class_t_h_b___plugin___exams_1_1_monitor.html", null ],
      [ "THB_Plugin_Exams.Monitor", "d9/d79/class_t_h_b___plugin___exams_1_1_monitor.html", null ],
      [ "THB_Plugin_Exams.Monitor", "d9/d79/class_t_h_b___plugin___exams_1_1_monitor.html", null ],
      [ "THB_Plugin_Exams.TestConstructor", "d4/d8d/class_t_h_b___plugin___exams_1_1_test_constructor.html", null ],
      [ "THB_Plugin_Exams.TestConstructor", "d4/d8d/class_t_h_b___plugin___exams_1_1_test_constructor.html", null ],
      [ "THB_Plugin_Exams.TestConstructor", "d4/d8d/class_t_h_b___plugin___exams_1_1_test_constructor.html", null ],
      [ "THB_Plugin_Exams.TestConstructor", "d4/d8d/class_t_h_b___plugin___exams_1_1_test_constructor.html", null ],
      [ "THB_Plugin_Exams.UserControl1", "d4/ddd/class_t_h_b___plugin___exams_1_1_user_control1.html", null ],
      [ "THB_Plugin_Lesson.Assesments", "d7/dc2/class_t_h_b___plugin___lesson_1_1_assesments.html", null ],
      [ "THB_Plugin_Lesson.Assesments", "d7/dc2/class_t_h_b___plugin___lesson_1_1_assesments.html", null ],
      [ "THB_Plugin_Lesson.Assesments", "d7/dc2/class_t_h_b___plugin___lesson_1_1_assesments.html", null ],
      [ "THB_Plugin_Lesson.Assesments", "d7/dc2/class_t_h_b___plugin___lesson_1_1_assesments.html", null ],
      [ "THB_Plugin_Lesson.AttendanceLog", "de/d96/class_t_h_b___plugin___lesson_1_1_attendance_log.html", null ],
      [ "THB_Plugin_Lesson.AttendanceLog", "de/d96/class_t_h_b___plugin___lesson_1_1_attendance_log.html", null ],
      [ "THB_Plugin_Lesson.AttendanceLog", "de/d96/class_t_h_b___plugin___lesson_1_1_attendance_log.html", null ],
      [ "THB_Plugin_Lesson.AttendanceLog", "de/d96/class_t_h_b___plugin___lesson_1_1_attendance_log.html", null ],
      [ "THB_Plugin_Lesson.LessonBoard", "d1/d3b/class_t_h_b___plugin___lesson_1_1_lesson_board.html", null ],
      [ "THB_Plugin_Lesson.LessonBoard", "d1/d3b/class_t_h_b___plugin___lesson_1_1_lesson_board.html", null ],
      [ "THB_Plugin_Lesson.LessonBoard", "d1/d3b/class_t_h_b___plugin___lesson_1_1_lesson_board.html", null ],
      [ "THB_Plugin_Lesson.LessonBoard", "d1/d3b/class_t_h_b___plugin___lesson_1_1_lesson_board.html", null ],
      [ "THB_Plugin_Lesson.LessonBoard", "d1/d3b/class_t_h_b___plugin___lesson_1_1_lesson_board.html", null ],
      [ "THB_Plugin_Lesson.Repository", "d1/df2/class_t_h_b___plugin___lesson_1_1_repository.html", null ],
      [ "THB_Plugin_Lesson.Repository", "d1/df2/class_t_h_b___plugin___lesson_1_1_repository.html", null ],
      [ "THB_Plugin_Lesson.Repository", "d1/df2/class_t_h_b___plugin___lesson_1_1_repository.html", null ],
      [ "THB_Plugin_Lesson.Repository", "d1/df2/class_t_h_b___plugin___lesson_1_1_repository.html", null ],
      [ "THB_Plugin_Lesson.UserControl1", "d4/dec/class_t_h_b___plugin___lesson_1_1_user_control1.html", null ],
      [ "THB_Plugin_Orders.AddOrder", "d4/d17/class_t_h_b___plugin___orders_1_1_add_order.html", null ],
      [ "THB_Plugin_Orders.AddOrder", "d4/d17/class_t_h_b___plugin___orders_1_1_add_order.html", null ],
      [ "THB_Plugin_Orders.AddOrder", "d4/d17/class_t_h_b___plugin___orders_1_1_add_order.html", null ],
      [ "THB_Plugin_Orders.AddOrder", "d4/d17/class_t_h_b___plugin___orders_1_1_add_order.html", null ],
      [ "THB_Plugin_Orders.OrdersBoard", "dd/d7c/class_t_h_b___plugin___orders_1_1_orders_board.html", null ],
      [ "THB_Plugin_Orders.OrdersBoard", "dd/d7c/class_t_h_b___plugin___orders_1_1_orders_board.html", null ],
      [ "THB_Plugin_Orders.OrdersBoard", "dd/d7c/class_t_h_b___plugin___orders_1_1_orders_board.html", null ],
      [ "THB_Plugin_Orders.OrdersBoard", "dd/d7c/class_t_h_b___plugin___orders_1_1_orders_board.html", null ],
      [ "THB_Plugin_Orders.UserControl1", "d2/dc6/class_t_h_b___plugin___orders_1_1_user_control1.html", null ],
      [ "THB_Plugin_Social.Achivments.Achivments", "d8/dcc/class_t_h_b___plugin___social_1_1_achivments_1_1_achivments.html", null ],
      [ "THB_Plugin_Social.Achivments.Achivments", "d8/dcc/class_t_h_b___plugin___social_1_1_achivments_1_1_achivments.html", null ],
      [ "THB_Plugin_Social.Achivments.Achivments", "d8/dcc/class_t_h_b___plugin___social_1_1_achivments_1_1_achivments.html", null ],
      [ "THB_Plugin_Social.Achivments.Achivments", "d8/dcc/class_t_h_b___plugin___social_1_1_achivments_1_1_achivments.html", null ],
      [ "THB_Plugin_Social.Advices.Advices", "dc/d36/class_t_h_b___plugin___social_1_1_advices_1_1_advices.html", null ],
      [ "THB_Plugin_Social.Advices.Advices", "dc/d36/class_t_h_b___plugin___social_1_1_advices_1_1_advices.html", null ],
      [ "THB_Plugin_Social.Advices.Advices", "dc/d36/class_t_h_b___plugin___social_1_1_advices_1_1_advices.html", null ],
      [ "THB_Plugin_Social.Advices.Advices", "dc/d36/class_t_h_b___plugin___social_1_1_advices_1_1_advices.html", null ],
      [ "THB_Plugin_Social.PersonalStatistic.PersonalStatistic", "d7/d60/class_t_h_b___plugin___social_1_1_personal_statistic_1_1_personal_statistic.html", null ],
      [ "THB_Plugin_Social.PersonalStatistic.PersonalStatistic", "d7/d60/class_t_h_b___plugin___social_1_1_personal_statistic_1_1_personal_statistic.html", null ],
      [ "THB_Plugin_Social.PersonalStatistic.PersonalStatistic", "d7/d60/class_t_h_b___plugin___social_1_1_personal_statistic_1_1_personal_statistic.html", null ],
      [ "THB_Plugin_Social.PersonalStatistic.PersonalStatistic", "d7/d60/class_t_h_b___plugin___social_1_1_personal_statistic_1_1_personal_statistic.html", null ],
      [ "THB_Plugin_Social.UserControl1", "d1/d79/class_t_h_b___plugin___social_1_1_user_control1.html", null ],
      [ "WpfHandler.UserControl1", "dd/d5d/class_wpf_handler_1_1_user_control1.html", null ]
    ] ],
    [ "PipesProvider.Networking.Info", "d7/d6e/class_pipes_provider_1_1_networking_1_1_info.html", null ],
    [ "PipesProvider.Networking.Routing.Instruction", "d5/d2e/class_pipes_provider_1_1_networking_1_1_routing_1_1_instruction.html", null ],
    [ "InternalTypeHelper", null, [
      [ "XamlGeneratedNamespace.GeneratedInternalTypeHelper", "dc/db0/class_xaml_generated_namespace_1_1_generated_internal_type_helper.html", null ],
      [ "XamlGeneratedNamespace.GeneratedInternalTypeHelper", "dc/db0/class_xaml_generated_namespace_1_1_generated_internal_type_helper.html", null ]
    ] ],
    [ "TeacherHandbook.Core.Orders.IOrder", "df/d8a/interface_teacher_handbook_1_1_core_1_1_orders_1_1_i_order.html", [
      [ "TeacherHandbook.Core.Orders.BaseOrder", "df/d39/class_teacher_handbook_1_1_core_1_1_orders_1_1_base_order.html", [
        [ "TeacherHandbook.Core.Orders.MentoringOrder", "d8/d91/class_teacher_handbook_1_1_core_1_1_orders_1_1_mentoring_order.html", null ]
      ] ]
    ] ],
    [ "UniformClient.Plugins.IPlugin", "d4/d25/interface_uniform_client_1_1_plugins_1_1_i_plugin.html", [
      [ "TeacherHandbook.Plugins.Feed.Feed", "d2/d56/class_teacher_handbook_1_1_plugins_1_1_feed_1_1_feed.html", null ],
      [ "TeacherHandbook.Plugins.Schedule.Schedule", "dc/d1d/class_teacher_handbook_1_1_plugins_1_1_schedule_1_1_schedule.html", null ],
      [ "THB_Plugin_Exams.Monitor", "d9/d79/class_t_h_b___plugin___exams_1_1_monitor.html", null ],
      [ "THB_Plugin_Exams.TestConstructor", "d4/d8d/class_t_h_b___plugin___exams_1_1_test_constructor.html", null ],
      [ "THB_Plugin_Lesson.Repository", "d1/df2/class_t_h_b___plugin___lesson_1_1_repository.html", null ],
      [ "THB_Plugin_Orders.OrdersBoard", "dd/d7c/class_t_h_b___plugin___orders_1_1_orders_board.html", null ],
      [ "THB_Plugin_Social.PersonalStatistic.PersonalStatistic", "d7/d60/class_t_h_b___plugin___social_1_1_personal_statistic_1_1_personal_statistic.html", null ]
    ] ],
    [ "IPlugin", null, [
      [ "THB_Plugin_Exams.ExamPlanner", "df/df8/class_t_h_b___plugin___exams_1_1_exam_planner.html", null ],
      [ "THB_Plugin_Lesson.Assesments", "d7/dc2/class_t_h_b___plugin___lesson_1_1_assesments.html", null ],
      [ "THB_Plugin_Lesson.AttendanceLog", "de/d96/class_t_h_b___plugin___lesson_1_1_attendance_log.html", null ],
      [ "THB_Plugin_Lesson.LessonBoard", "d1/d3b/class_t_h_b___plugin___lesson_1_1_lesson_board.html", null ],
      [ "THB_Plugin_Orders.AddOrder", "d4/d17/class_t_h_b___plugin___orders_1_1_add_order.html", null ],
      [ "THB_Plugin_Social.Achivments.Achivments", "d8/dcc/class_t_h_b___plugin___social_1_1_achivments_1_1_achivments.html", null ],
      [ "THB_Plugin_Social.Advices.Advices", "dc/d36/class_t_h_b___plugin___social_1_1_advices_1_1_advices.html", null ]
    ] ],
    [ "UniformQueries.IQueryHandlerProcessor", "d4/dc9/interface_uniform_queries_1_1_i_query_handler_processor.html", [
      [ "THB_Data_Server_Queries.GET_DAYS_RANGE", "de/de2/class_t_h_b___data___server___queries_1_1_g_e_t___d_a_y_s___r_a_n_g_e.html", null ],
      [ "UniformServer.Queries.GET_PUBLIC_KEY", "da/d43/class_uniform_server_1_1_queries_1_1_g_e_t___p_u_b_l_i_c___k_e_y.html", null ]
    ] ],
    [ "TeacherHandbook.Core.Containers.Entities.IUser", "d1/dfc/interface_teacher_handbook_1_1_core_1_1_containers_1_1_entities_1_1_i_user.html", [
      [ "TeacherHandbook.Core.Containers.Entities.BaseUser", "d2/dbe/class_teacher_handbook_1_1_core_1_1_containers_1_1_entities_1_1_base_user.html", [
        [ "TeacherHandbook.Core.Containers.Entities.Teacher", "d5/d63/class_teacher_handbook_1_1_core_1_1_containers_1_1_entities_1_1_teacher.html", null ]
      ] ]
    ] ],
    [ "TeacherHandbook.Core.Localization.LanguageContaier", "db/dd2/class_teacher_handbook_1_1_core_1_1_localization_1_1_language_contaier.html", null ],
    [ "TeacherHandbook.Core.Containers.Schedule.Logbook", "d5/d0e/class_teacher_handbook_1_1_core_1_1_containers_1_1_schedule_1_1_logbook.html", null ],
    [ "PipesProvider.Security.LogonConfig", "df/d6d/struct_pipes_provider_1_1_security_1_1_logon_config.html", null ],
    [ "PipesProvider.Security.LSA.LSA_OBJECT_ATTRIBUTES", "dd/dd5/struct_pipes_provider_1_1_security_1_1_l_s_a_1_1_l_s_a___o_b_j_e_c_t___a_t_t_r_i_b_u_t_e_s.html", null ],
    [ "PipesProvider.Security.LSA.LSA_UNICODE_STRING", "d7/df5/struct_pipes_provider_1_1_security_1_1_l_s_a_1_1_l_s_a___u_n_i_c_o_d_e___s_t_r_i_n_g.html", null ],
    [ "PipesProvider.Security.LSA.LsaSecurityWrapper", "de/d2d/class_pipes_provider_1_1_security_1_1_l_s_a_1_1_lsa_security_wrapper.html", null ],
    [ "UniformClient.Plugins.MenuItemMeta", "dd/db0/class_uniform_client_1_1_plugins_1_1_menu_item_meta.html", null ],
    [ "TeacherHandbook.Core.Containers.CrossTypes.NameContainer", "d0/d8b/class_teacher_handbook_1_1_core_1_1_containers_1_1_cross_types_1_1_name_container.html", null ],
    [ "TeacherHandbook.Core.Orders.OrderDate", "dc/d14/struct_teacher_handbook_1_1_core_1_1_orders_1_1_order_date.html", null ],
    [ "ConsoleDraw.Primitives", "db/d7f/class_console_draw_1_1_primitives.html", null ],
    [ "PipesProvider.Handlers.Query", "d2/db8/class_pipes_provider_1_1_handlers_1_1_query.html", null ],
    [ "PipesProvider.Client.QueryContainer", "d0/dc9/struct_pipes_provider_1_1_client_1_1_query_container.html", null ],
    [ "UniformQueries.QueryPart", "d5/d61/struct_uniform_queries_1_1_query_part.html", null ],
    [ "TeacherHandbook.Properties.Resources", "de/d69/class_teacher_handbook_1_1_properties_1_1_resources.html", null ],
    [ "THB_Plugin_Lesson.Properties.Resources", "d1/d04/class_t_h_b___plugin___lesson_1_1_properties_1_1_resources.html", null ],
    [ "THB_Plugin_Orders.Properties.Resources", "d6/d74/class_t_h_b___plugin___orders_1_1_properties_1_1_resources.html", null ],
    [ "THB_Plugin_Exams.Properties.Resources", "d8/d18/class_t_h_b___plugin___exams_1_1_properties_1_1_resources.html", null ],
    [ "WpfHandler.Properties.Resources", "d2/d90/class_wpf_handler_1_1_properties_1_1_resources.html", null ],
    [ "THB_Plugin_Social.Properties.Resources", "d9/df5/class_t_h_b___plugin___social_1_1_properties_1_1_resources.html", null ],
    [ "THB_Data_Server.Properties.Resources", "d1/d40/class_t_h_b___data___server_1_1_properties_1_1_resources.html", null ],
    [ "PipesProvider.Networking.Routing.RoutingTable", "d3/d3a/class_pipes_provider_1_1_networking_1_1_routing_1_1_routing_table.html", null ],
    [ "PipesProvider.Server.ServerAPI", "d5/d17/class_pipes_provider_1_1_server_1_1_server_a_p_i.html", null ],
    [ "PipesProvider.Server.ServerTransmissionController", "d6/d8d/class_pipes_provider_1_1_server_1_1_server_transmission_controller.html", null ],
    [ "PipesProvider.Handlers.Service", "dd/d9c/class_pipes_provider_1_1_handlers_1_1_service.html", null ],
    [ "TeacherHandbook.Core.Containers.Schedule.Session", "d5/d8e/class_teacher_handbook_1_1_core_1_1_containers_1_1_schedule_1_1_session.html", null ],
    [ "TeacherHandbook.Core.Containers.Schedule.Subject", "db/dce/class_teacher_handbook_1_1_core_1_1_containers_1_1_schedule_1_1_subject.html", null ],
    [ "PipesProvider.Client.TransmissionLine", "da/d0e/class_pipes_provider_1_1_client_1_1_transmission_line.html", null ],
    [ "UserControl", null, [
      [ "TeacherHandbook.CatalogButton", "d2/d3e/class_teacher_handbook_1_1_catalog_button.html", null ],
      [ "TeacherHandbook.Controls.CatalogButton", "df/d61/class_teacher_handbook_1_1_controls_1_1_catalog_button.html", null ],
      [ "TeacherHandbook.Controls.CatalogButton", "df/d61/class_teacher_handbook_1_1_controls_1_1_catalog_button.html", null ],
      [ "TeacherHandbook.Controls.CatalogButton", "df/d61/class_teacher_handbook_1_1_controls_1_1_catalog_button.html", null ],
      [ "TeacherHandbook.Controls.CatalogButton", "df/d61/class_teacher_handbook_1_1_controls_1_1_catalog_button.html", null ],
      [ "TeacherHandbook.Controls.CatalogButton", "df/d61/class_teacher_handbook_1_1_controls_1_1_catalog_button.html", null ],
      [ "TeacherHandbook.Controls.UserControl1", "d6/dc1/class_teacher_handbook_1_1_controls_1_1_user_control1.html", null ],
      [ "TeacherHandbook.Plugins.Feed.Feed", "d2/d56/class_teacher_handbook_1_1_plugins_1_1_feed_1_1_feed.html", null ],
      [ "TeacherHandbook.Plugins.Feed.Feed", "d2/d56/class_teacher_handbook_1_1_plugins_1_1_feed_1_1_feed.html", null ],
      [ "TeacherHandbook.Plugins.Feed.Feed", "d2/d56/class_teacher_handbook_1_1_plugins_1_1_feed_1_1_feed.html", null ],
      [ "TeacherHandbook.Plugins.Feed.Feed", "d2/d56/class_teacher_handbook_1_1_plugins_1_1_feed_1_1_feed.html", null ],
      [ "TeacherHandbook.Plugins.Feed.Feed", "d2/d56/class_teacher_handbook_1_1_plugins_1_1_feed_1_1_feed.html", null ],
      [ "TeacherHandbook.Plugins.Feed.Feed", "d2/d56/class_teacher_handbook_1_1_plugins_1_1_feed_1_1_feed.html", null ],
      [ "TeacherHandbook.Plugins.Feed.Feed", "d2/d56/class_teacher_handbook_1_1_plugins_1_1_feed_1_1_feed.html", null ],
      [ "TeacherHandbook.Plugins.Feed.Feed", "d2/d56/class_teacher_handbook_1_1_plugins_1_1_feed_1_1_feed.html", null ],
      [ "TeacherHandbook.Plugins.Schedule.Schedule", "dc/d1d/class_teacher_handbook_1_1_plugins_1_1_schedule_1_1_schedule.html", null ],
      [ "TeacherHandbook.Plugins.Schedule.Schedule", "dc/d1d/class_teacher_handbook_1_1_plugins_1_1_schedule_1_1_schedule.html", null ],
      [ "TeacherHandbook.Plugins.Schedule.Schedule", "dc/d1d/class_teacher_handbook_1_1_plugins_1_1_schedule_1_1_schedule.html", null ],
      [ "TeacherHandbook.Plugins.Schedule.Schedule", "dc/d1d/class_teacher_handbook_1_1_plugins_1_1_schedule_1_1_schedule.html", null ],
      [ "TeacherHandbook.Plugins.Schedule.Schedule", "dc/d1d/class_teacher_handbook_1_1_plugins_1_1_schedule_1_1_schedule.html", null ],
      [ "TeacherHandbook.Plugins.Schedule.Schedule", "dc/d1d/class_teacher_handbook_1_1_plugins_1_1_schedule_1_1_schedule.html", null ],
      [ "THB_Plugin_Exams.ExamPlanner", "df/df8/class_t_h_b___plugin___exams_1_1_exam_planner.html", null ],
      [ "THB_Plugin_Exams.ExamPlanner", "df/df8/class_t_h_b___plugin___exams_1_1_exam_planner.html", null ],
      [ "THB_Plugin_Exams.ExamPlanner", "df/df8/class_t_h_b___plugin___exams_1_1_exam_planner.html", null ],
      [ "THB_Plugin_Exams.ExamPlanner", "df/df8/class_t_h_b___plugin___exams_1_1_exam_planner.html", null ],
      [ "THB_Plugin_Exams.ExamPlanner", "df/df8/class_t_h_b___plugin___exams_1_1_exam_planner.html", null ],
      [ "THB_Plugin_Exams.Monitor", "d9/d79/class_t_h_b___plugin___exams_1_1_monitor.html", null ],
      [ "THB_Plugin_Exams.Monitor", "d9/d79/class_t_h_b___plugin___exams_1_1_monitor.html", null ],
      [ "THB_Plugin_Exams.Monitor", "d9/d79/class_t_h_b___plugin___exams_1_1_monitor.html", null ],
      [ "THB_Plugin_Exams.Monitor", "d9/d79/class_t_h_b___plugin___exams_1_1_monitor.html", null ],
      [ "THB_Plugin_Exams.Monitor", "d9/d79/class_t_h_b___plugin___exams_1_1_monitor.html", null ],
      [ "THB_Plugin_Exams.TestConstructor", "d4/d8d/class_t_h_b___plugin___exams_1_1_test_constructor.html", null ],
      [ "THB_Plugin_Exams.TestConstructor", "d4/d8d/class_t_h_b___plugin___exams_1_1_test_constructor.html", null ],
      [ "THB_Plugin_Exams.TestConstructor", "d4/d8d/class_t_h_b___plugin___exams_1_1_test_constructor.html", null ],
      [ "THB_Plugin_Exams.TestConstructor", "d4/d8d/class_t_h_b___plugin___exams_1_1_test_constructor.html", null ],
      [ "THB_Plugin_Exams.TestConstructor", "d4/d8d/class_t_h_b___plugin___exams_1_1_test_constructor.html", null ],
      [ "THB_Plugin_Exams.UserControl1", "d4/ddd/class_t_h_b___plugin___exams_1_1_user_control1.html", null ],
      [ "THB_Plugin_Lesson.Assesments", "d7/dc2/class_t_h_b___plugin___lesson_1_1_assesments.html", null ],
      [ "THB_Plugin_Lesson.Assesments", "d7/dc2/class_t_h_b___plugin___lesson_1_1_assesments.html", null ],
      [ "THB_Plugin_Lesson.Assesments", "d7/dc2/class_t_h_b___plugin___lesson_1_1_assesments.html", null ],
      [ "THB_Plugin_Lesson.Assesments", "d7/dc2/class_t_h_b___plugin___lesson_1_1_assesments.html", null ],
      [ "THB_Plugin_Lesson.Assesments", "d7/dc2/class_t_h_b___plugin___lesson_1_1_assesments.html", null ],
      [ "THB_Plugin_Lesson.AttendanceLog", "de/d96/class_t_h_b___plugin___lesson_1_1_attendance_log.html", null ],
      [ "THB_Plugin_Lesson.AttendanceLog", "de/d96/class_t_h_b___plugin___lesson_1_1_attendance_log.html", null ],
      [ "THB_Plugin_Lesson.AttendanceLog", "de/d96/class_t_h_b___plugin___lesson_1_1_attendance_log.html", null ],
      [ "THB_Plugin_Lesson.AttendanceLog", "de/d96/class_t_h_b___plugin___lesson_1_1_attendance_log.html", null ],
      [ "THB_Plugin_Lesson.AttendanceLog", "de/d96/class_t_h_b___plugin___lesson_1_1_attendance_log.html", null ],
      [ "THB_Plugin_Lesson.LessonBoard", "d1/d3b/class_t_h_b___plugin___lesson_1_1_lesson_board.html", null ],
      [ "THB_Plugin_Lesson.LessonBoard", "d1/d3b/class_t_h_b___plugin___lesson_1_1_lesson_board.html", null ],
      [ "THB_Plugin_Lesson.LessonBoard", "d1/d3b/class_t_h_b___plugin___lesson_1_1_lesson_board.html", null ],
      [ "THB_Plugin_Lesson.LessonBoard", "d1/d3b/class_t_h_b___plugin___lesson_1_1_lesson_board.html", null ],
      [ "THB_Plugin_Lesson.LessonBoard", "d1/d3b/class_t_h_b___plugin___lesson_1_1_lesson_board.html", null ],
      [ "THB_Plugin_Lesson.LessonBoard", "d1/d3b/class_t_h_b___plugin___lesson_1_1_lesson_board.html", null ],
      [ "THB_Plugin_Lesson.Repository", "d1/df2/class_t_h_b___plugin___lesson_1_1_repository.html", null ],
      [ "THB_Plugin_Lesson.Repository", "d1/df2/class_t_h_b___plugin___lesson_1_1_repository.html", null ],
      [ "THB_Plugin_Lesson.Repository", "d1/df2/class_t_h_b___plugin___lesson_1_1_repository.html", null ],
      [ "THB_Plugin_Lesson.Repository", "d1/df2/class_t_h_b___plugin___lesson_1_1_repository.html", null ],
      [ "THB_Plugin_Lesson.Repository", "d1/df2/class_t_h_b___plugin___lesson_1_1_repository.html", null ],
      [ "THB_Plugin_Lesson.UserControl1", "d4/dec/class_t_h_b___plugin___lesson_1_1_user_control1.html", null ],
      [ "THB_Plugin_Orders.AddOrder", "d4/d17/class_t_h_b___plugin___orders_1_1_add_order.html", null ],
      [ "THB_Plugin_Orders.AddOrder", "d4/d17/class_t_h_b___plugin___orders_1_1_add_order.html", null ],
      [ "THB_Plugin_Orders.AddOrder", "d4/d17/class_t_h_b___plugin___orders_1_1_add_order.html", null ],
      [ "THB_Plugin_Orders.AddOrder", "d4/d17/class_t_h_b___plugin___orders_1_1_add_order.html", null ],
      [ "THB_Plugin_Orders.AddOrder", "d4/d17/class_t_h_b___plugin___orders_1_1_add_order.html", null ],
      [ "THB_Plugin_Orders.OrdersBoard", "dd/d7c/class_t_h_b___plugin___orders_1_1_orders_board.html", null ],
      [ "THB_Plugin_Orders.OrdersBoard", "dd/d7c/class_t_h_b___plugin___orders_1_1_orders_board.html", null ],
      [ "THB_Plugin_Orders.OrdersBoard", "dd/d7c/class_t_h_b___plugin___orders_1_1_orders_board.html", null ],
      [ "THB_Plugin_Orders.OrdersBoard", "dd/d7c/class_t_h_b___plugin___orders_1_1_orders_board.html", null ],
      [ "THB_Plugin_Orders.OrdersBoard", "dd/d7c/class_t_h_b___plugin___orders_1_1_orders_board.html", null ],
      [ "THB_Plugin_Orders.UserControl1", "d2/dc6/class_t_h_b___plugin___orders_1_1_user_control1.html", null ],
      [ "THB_Plugin_Social.Achivments.Achivments", "d8/dcc/class_t_h_b___plugin___social_1_1_achivments_1_1_achivments.html", null ],
      [ "THB_Plugin_Social.Achivments.Achivments", "d8/dcc/class_t_h_b___plugin___social_1_1_achivments_1_1_achivments.html", null ],
      [ "THB_Plugin_Social.Achivments.Achivments", "d8/dcc/class_t_h_b___plugin___social_1_1_achivments_1_1_achivments.html", null ],
      [ "THB_Plugin_Social.Achivments.Achivments", "d8/dcc/class_t_h_b___plugin___social_1_1_achivments_1_1_achivments.html", null ],
      [ "THB_Plugin_Social.Achivments.Achivments", "d8/dcc/class_t_h_b___plugin___social_1_1_achivments_1_1_achivments.html", null ],
      [ "THB_Plugin_Social.Advices.Advices", "dc/d36/class_t_h_b___plugin___social_1_1_advices_1_1_advices.html", null ],
      [ "THB_Plugin_Social.Advices.Advices", "dc/d36/class_t_h_b___plugin___social_1_1_advices_1_1_advices.html", null ],
      [ "THB_Plugin_Social.Advices.Advices", "dc/d36/class_t_h_b___plugin___social_1_1_advices_1_1_advices.html", null ],
      [ "THB_Plugin_Social.Advices.Advices", "dc/d36/class_t_h_b___plugin___social_1_1_advices_1_1_advices.html", null ],
      [ "THB_Plugin_Social.Advices.Advices", "dc/d36/class_t_h_b___plugin___social_1_1_advices_1_1_advices.html", null ],
      [ "THB_Plugin_Social.PersonalStatistic.PersonalStatistic", "d7/d60/class_t_h_b___plugin___social_1_1_personal_statistic_1_1_personal_statistic.html", null ],
      [ "THB_Plugin_Social.PersonalStatistic.PersonalStatistic", "d7/d60/class_t_h_b___plugin___social_1_1_personal_statistic_1_1_personal_statistic.html", null ],
      [ "THB_Plugin_Social.PersonalStatistic.PersonalStatistic", "d7/d60/class_t_h_b___plugin___social_1_1_personal_statistic_1_1_personal_statistic.html", null ],
      [ "THB_Plugin_Social.PersonalStatistic.PersonalStatistic", "d7/d60/class_t_h_b___plugin___social_1_1_personal_statistic_1_1_personal_statistic.html", null ],
      [ "THB_Plugin_Social.PersonalStatistic.PersonalStatistic", "d7/d60/class_t_h_b___plugin___social_1_1_personal_statistic_1_1_personal_statistic.html", null ],
      [ "THB_Plugin_Social.UserControl1", "d1/d79/class_t_h_b___plugin___social_1_1_user_control1.html", null ],
      [ "WpfHandler.UserControl1", "dd/d5d/class_wpf_handler_1_1_user_control1.html", null ]
    ] ],
    [ "TeacherHandbook.Core.Containers.Schedule.Week", "de/d25/class_teacher_handbook_1_1_core_1_1_containers_1_1_schedule_1_1_week.html", null ],
    [ "Window", null, [
      [ "TeacherHandbook.MainWindow", "df/d32/class_teacher_handbook_1_1_main_window.html", null ],
      [ "TeacherHandbook.MainWindow", "df/d32/class_teacher_handbook_1_1_main_window.html", null ],
      [ "TeacherHandbook.MainWindow", "df/d32/class_teacher_handbook_1_1_main_window.html", null ],
      [ "TeacherHandbook.MainWindow", "df/d32/class_teacher_handbook_1_1_main_window.html", null ],
      [ "TeacherHandbook.MainWindow", "df/d32/class_teacher_handbook_1_1_main_window.html", null ]
    ] ]
];