var searchData=
[
  ['catalogbutton_5fclick',['CatalogButton_Click',['../df/d61/class_teacher_handbook_1_1_controls_1_1_catalog_button.html#ab6fdcafe2b97c645486d1ca83109c979',1,'TeacherHandbook::Controls::CatalogButton']]],
  ['clientloop',['ClientLoop',['../d4/ddf/class_pipes_provider_1_1_a_p_i.html#aaccf777b3b489b550739dd8adcf4a1d3',1,'PipesProvider::API']]],
  ['clienttoserverloop',['ClientToServerLoop',['../d4/ddf/class_pipes_provider_1_1_a_p_i.html#a99feebefadd9a40a3c1fa7175324d950',1,'PipesProvider.API.ClientToServerLoop(System.Action&lt; ServerTransmissionMeta, string &gt; queryHandlerCallback, string pipeName, out string guid)'],['../d4/ddf/class_pipes_provider_1_1_a_p_i.html#a06ee04a0e80238a176b7b2cac3f6bb4b',1,'PipesProvider.API.ClientToServerLoop(string guid, System.Action&lt; ServerTransmissionMeta, string &gt; queryHandlerCallback, string pipeName)'],['../d4/ddf/class_pipes_provider_1_1_a_p_i.html#a740e60d5cfd04fcc434e05b40910e493',1,'PipesProvider.API.ClientToServerLoop(string guid, System.Action&lt; ServerTransmissionMeta, string &gt; queryHandlerCallback, string pipeName, int allowedServerInstances)'],['../d4/ddf/class_pipes_provider_1_1_a_p_i.html#a9eacd5177e24badabe5ac8a3fe30d5d3',1,'PipesProvider.API.ClientToServerLoop(string guid, System.Action&lt; ServerTransmissionMeta, string &gt; queryHandlerCallback, string pipeName, PipeDirection pipeDirection, int allowedServerInstances, PipeTransmissionMode transmissionMode, PipeOptions pipeOptions)']]],
  ['close',['Close',['../d1/d09/class_pipes_provider_1_1_transmission_line.html#a4aa28b1d29a2b0b6fb2af6f046fdf56a',1,'PipesProvider::TransmissionLine']]],
  ['commandresponseprocessor',['CommandResponseProcessor',['../d6/d8f/class_t_h_b___data___server_1_1_commands.html#a996531160e55feb986342fac81c89d71',1,'THB_Data_Server::Commands']]],
  ['connectionestablishedcallbackretranslator',['ConnectionEstablishedCallbackRetranslator',['../d4/ddf/class_pipes_provider_1_1_a_p_i.html#a0feeed2f76dc4292c3b85fdd054bd77e',1,'PipesProvider::API']]],
  ['connecttoserverasync',['ConnectToServerAsync',['../d4/ddf/class_pipes_provider_1_1_a_p_i.html#a5314727d43f5fafc8630dbc814cebeac',1,'PipesProvider::API']]],
  ['copy',['Copy',['../d2/d85/struct_pipes_provider_1_1_query_container.html#a4b91c3b8947613c8326451df7a1ff2a0',1,'PipesProvider::QueryContainer']]],
  ['createdelegate',['CreateDelegate',['../dc/db0/class_xaml_generated_namespace_1_1_generated_internal_type_helper.html#a8ec4c37e82d9f4e867e9655f4eac3a78',1,'XamlGeneratedNamespace.GeneratedInternalTypeHelper.CreateDelegate(System.Type delegateType, object target, string handler)'],['../dc/db0/class_xaml_generated_namespace_1_1_generated_internal_type_helper.html#a8ec4c37e82d9f4e867e9655f4eac3a78',1,'XamlGeneratedNamespace.GeneratedInternalTypeHelper.CreateDelegate(System.Type delegateType, object target, string handler)'],['../dc/db0/class_xaml_generated_namespace_1_1_generated_internal_type_helper.html#a8ec4c37e82d9f4e867e9655f4eac3a78',1,'XamlGeneratedNamespace.GeneratedInternalTypeHelper.CreateDelegate(System.Type delegateType, object target, string handler)']]],
  ['createinstance',['CreateInstance',['../dc/db0/class_xaml_generated_namespace_1_1_generated_internal_type_helper.html#aefb7a98fceb9c287cef4756942f441d1',1,'XamlGeneratedNamespace.GeneratedInternalTypeHelper.CreateInstance(System.Type type, System.Globalization.CultureInfo culture)'],['../dc/db0/class_xaml_generated_namespace_1_1_generated_internal_type_helper.html#aefb7a98fceb9c287cef4756942f441d1',1,'XamlGeneratedNamespace.GeneratedInternalTypeHelper.CreateInstance(System.Type type, System.Globalization.CultureInfo culture)'],['../dc/db0/class_xaml_generated_namespace_1_1_generated_internal_type_helper.html#aefb7a98fceb9c287cef4756942f441d1',1,'XamlGeneratedNamespace.GeneratedInternalTypeHelper.CreateInstance(System.Type type, System.Globalization.CultureInfo culture)']]]
];
