var hierarchy =
[
    [ "WpfHandler.Plugins.API", "d2/d9a/class_wpf_handler_1_1_plugins_1_1_a_p_i.html", null ],
    [ "Application", null, [
      [ "TeacherHandbook.App", "d2/d56/class_teacher_handbook_1_1_app.html", null ],
      [ "TeacherHandbook.App", "d2/d56/class_teacher_handbook_1_1_app.html", null ],
      [ "TeacherHandbook.App", "d2/d56/class_teacher_handbook_1_1_app.html", null ],
      [ "TeacherHandbook.App", "d2/d56/class_teacher_handbook_1_1_app.html", null ],
      [ "TeacherHandbook.App", "d2/d56/class_teacher_handbook_1_1_app.html", null ]
    ] ],
    [ "ApplicationSettingsBase", null, [
      [ "TeacherHandbook.Properties.Settings", "d0/d4b/class_teacher_handbook_1_1_properties_1_1_settings.html", null ],
      [ "THB_Plugin_Exams.Properties.Settings", "dc/d5b/class_t_h_b___plugin___exams_1_1_properties_1_1_settings.html", null ],
      [ "THB_Plugin_Lesson.Properties.Settings", "d2/d6c/class_t_h_b___plugin___lesson_1_1_properties_1_1_settings.html", null ],
      [ "THB_Plugin_Orders.Properties.Settings", "dd/d9e/class_t_h_b___plugin___orders_1_1_properties_1_1_settings.html", null ],
      [ "THB_Plugin_Social.Properties.Settings", "d5/dbf/class_t_h_b___plugin___social_1_1_properties_1_1_settings.html", null ],
      [ "WpfHandler.Properties.Settings", "d7/d4f/class_wpf_handler_1_1_properties_1_1_settings.html", null ]
    ] ],
    [ "BaseClient", null, [
      [ "TeacherHandbook.Client", "d8/de3/class_teacher_handbook_1_1_client.html", null ]
    ] ],
    [ "BaseServer", null, [
      [ "THB_Data_Server.Server", "dc/d42/class_t_h_b___data___server_1_1_server.html", null ]
    ] ],
    [ "TeacherHandbook.Core.Containers.Schedule.Day", "d5/d0b/class_teacher_handbook_1_1_core_1_1_containers_1_1_schedule_1_1_day.html", null ],
    [ "TeacherHandbook.Client.DomainContainer", "db/de2/class_teacher_handbook_1_1_client_1_1_domain_container.html", null ],
    [ "TeacherHandbook.Core.Containers.Entities.Group", "da/dfa/class_teacher_handbook_1_1_core_1_1_containers_1_1_entities_1_1_group.html", null ],
    [ "IComponentConnector", null, [
      [ "TeacherHandbook.CatalogButton", "d2/d3e/class_teacher_handbook_1_1_catalog_button.html", null ],
      [ "TeacherHandbook.Controls.CatalogButton", "df/d61/class_teacher_handbook_1_1_controls_1_1_catalog_button.html", null ],
      [ "TeacherHandbook.Controls.CatalogButton", "df/d61/class_teacher_handbook_1_1_controls_1_1_catalog_button.html", null ],
      [ "TeacherHandbook.Controls.CatalogButton", "df/d61/class_teacher_handbook_1_1_controls_1_1_catalog_button.html", null ],
      [ "TeacherHandbook.Controls.CatalogButton", "df/d61/class_teacher_handbook_1_1_controls_1_1_catalog_button.html", null ],
      [ "TeacherHandbook.Controls.UserControl1", "d6/dc1/class_teacher_handbook_1_1_controls_1_1_user_control1.html", null ],
      [ "TeacherHandbook.MainWindow", "df/d32/class_teacher_handbook_1_1_main_window.html", null ],
      [ "TeacherHandbook.MainWindow", "df/d32/class_teacher_handbook_1_1_main_window.html", null ],
      [ "TeacherHandbook.MainWindow", "df/d32/class_teacher_handbook_1_1_main_window.html", null ],
      [ "TeacherHandbook.MainWindow", "df/d32/class_teacher_handbook_1_1_main_window.html", null ],
      [ "TeacherHandbook.Plugins.Feed.Feed", "d2/d56/class_teacher_handbook_1_1_plugins_1_1_feed_1_1_feed.html", null ],
      [ "TeacherHandbook.Plugins.Feed.Feed", "d2/d56/class_teacher_handbook_1_1_plugins_1_1_feed_1_1_feed.html", null ],
      [ "TeacherHandbook.Plugins.Feed.Feed", "d2/d56/class_teacher_handbook_1_1_plugins_1_1_feed_1_1_feed.html", null ],
      [ "TeacherHandbook.Plugins.Feed.Feed", "d2/d56/class_teacher_handbook_1_1_plugins_1_1_feed_1_1_feed.html", null ],
      [ "TeacherHandbook.Plugins.Feed.Feed", "d2/d56/class_teacher_handbook_1_1_plugins_1_1_feed_1_1_feed.html", null ],
      [ "TeacherHandbook.Plugins.Feed.Feed", "d2/d56/class_teacher_handbook_1_1_plugins_1_1_feed_1_1_feed.html", null ],
      [ "TeacherHandbook.Plugins.Feed.Feed", "d2/d56/class_teacher_handbook_1_1_plugins_1_1_feed_1_1_feed.html", null ],
      [ "TeacherHandbook.Plugins.Schedule.Schedule", "dc/d1d/class_teacher_handbook_1_1_plugins_1_1_schedule_1_1_schedule.html", null ],
      [ "TeacherHandbook.Plugins.Schedule.Schedule", "dc/d1d/class_teacher_handbook_1_1_plugins_1_1_schedule_1_1_schedule.html", null ],
      [ "TeacherHandbook.Plugins.Schedule.Schedule", "dc/d1d/class_teacher_handbook_1_1_plugins_1_1_schedule_1_1_schedule.html", null ],
      [ "TeacherHandbook.Plugins.Schedule.Schedule", "dc/d1d/class_teacher_handbook_1_1_plugins_1_1_schedule_1_1_schedule.html", null ],
      [ "TeacherHandbook.Plugins.Schedule.Schedule", "dc/d1d/class_teacher_handbook_1_1_plugins_1_1_schedule_1_1_schedule.html", null ],
      [ "THB_Plugin_Exams.ExamPlanner", "df/df8/class_t_h_b___plugin___exams_1_1_exam_planner.html", null ],
      [ "THB_Plugin_Exams.ExamPlanner", "df/df8/class_t_h_b___plugin___exams_1_1_exam_planner.html", null ],
      [ "THB_Plugin_Exams.ExamPlanner", "df/df8/class_t_h_b___plugin___exams_1_1_exam_planner.html", null ],
      [ "THB_Plugin_Exams.ExamPlanner", "df/df8/class_t_h_b___plugin___exams_1_1_exam_planner.html", null ],
      [ "THB_Plugin_Exams.Monitor", "d9/d79/class_t_h_b___plugin___exams_1_1_monitor.html", null ],
      [ "THB_Plugin_Exams.Monitor", "d9/d79/class_t_h_b___plugin___exams_1_1_monitor.html", null ],
      [ "THB_Plugin_Exams.Monitor", "d9/d79/class_t_h_b___plugin___exams_1_1_monitor.html", null ],
      [ "THB_Plugin_Exams.Monitor", "d9/d79/class_t_h_b___plugin___exams_1_1_monitor.html", null ],
      [ "THB_Plugin_Exams.TestConstructor", "d4/d8d/class_t_h_b___plugin___exams_1_1_test_constructor.html", null ],
      [ "THB_Plugin_Exams.TestConstructor", "d4/d8d/class_t_h_b___plugin___exams_1_1_test_constructor.html", null ],
      [ "THB_Plugin_Exams.TestConstructor", "d4/d8d/class_t_h_b___plugin___exams_1_1_test_constructor.html", null ],
      [ "THB_Plugin_Exams.TestConstructor", "d4/d8d/class_t_h_b___plugin___exams_1_1_test_constructor.html", null ],
      [ "THB_Plugin_Exams.UserControl1", "d4/ddd/class_t_h_b___plugin___exams_1_1_user_control1.html", null ],
      [ "THB_Plugin_Lesson.Assesments", "d7/dc2/class_t_h_b___plugin___lesson_1_1_assesments.html", null ],
      [ "THB_Plugin_Lesson.Assesments", "d7/dc2/class_t_h_b___plugin___lesson_1_1_assesments.html", null ],
      [ "THB_Plugin_Lesson.Assesments", "d7/dc2/class_t_h_b___plugin___lesson_1_1_assesments.html", null ],
      [ "THB_Plugin_Lesson.Assesments", "d7/dc2/class_t_h_b___plugin___lesson_1_1_assesments.html", null ],
      [ "THB_Plugin_Lesson.AttendanceLog", "de/d96/class_t_h_b___plugin___lesson_1_1_attendance_log.html", null ],
      [ "THB_Plugin_Lesson.AttendanceLog", "de/d96/class_t_h_b___plugin___lesson_1_1_attendance_log.html", null ],
      [ "THB_Plugin_Lesson.AttendanceLog", "de/d96/class_t_h_b___plugin___lesson_1_1_attendance_log.html", null ],
      [ "THB_Plugin_Lesson.AttendanceLog", "de/d96/class_t_h_b___plugin___lesson_1_1_attendance_log.html", null ],
      [ "THB_Plugin_Lesson.LessonBoard", "d1/d3b/class_t_h_b___plugin___lesson_1_1_lesson_board.html", null ],
      [ "THB_Plugin_Lesson.LessonBoard", "d1/d3b/class_t_h_b___plugin___lesson_1_1_lesson_board.html", null ],
      [ "THB_Plugin_Lesson.LessonBoard", "d1/d3b/class_t_h_b___plugin___lesson_1_1_lesson_board.html", null ],
      [ "THB_Plugin_Lesson.LessonBoard", "d1/d3b/class_t_h_b___plugin___lesson_1_1_lesson_board.html", null ],
      [ "THB_Plugin_Lesson.LessonBoard", "d1/d3b/class_t_h_b___plugin___lesson_1_1_lesson_board.html", null ],
      [ "THB_Plugin_Lesson.Repository", "d1/df2/class_t_h_b___plugin___lesson_1_1_repository.html", null ],
      [ "THB_Plugin_Lesson.Repository", "d1/df2/class_t_h_b___plugin___lesson_1_1_repository.html", null ],
      [ "THB_Plugin_Lesson.Repository", "d1/df2/class_t_h_b___plugin___lesson_1_1_repository.html", null ],
      [ "THB_Plugin_Lesson.Repository", "d1/df2/class_t_h_b___plugin___lesson_1_1_repository.html", null ],
      [ "THB_Plugin_Lesson.UserControl1", "d4/dec/class_t_h_b___plugin___lesson_1_1_user_control1.html", null ],
      [ "THB_Plugin_Orders.AddOrder", "d4/d17/class_t_h_b___plugin___orders_1_1_add_order.html", null ],
      [ "THB_Plugin_Orders.AddOrder", "d4/d17/class_t_h_b___plugin___orders_1_1_add_order.html", null ],
      [ "THB_Plugin_Orders.AddOrder", "d4/d17/class_t_h_b___plugin___orders_1_1_add_order.html", null ],
      [ "THB_Plugin_Orders.AddOrder", "d4/d17/class_t_h_b___plugin___orders_1_1_add_order.html", null ],
      [ "THB_Plugin_Orders.OrdersBoard", "dd/d7c/class_t_h_b___plugin___orders_1_1_orders_board.html", null ],
      [ "THB_Plugin_Orders.OrdersBoard", "dd/d7c/class_t_h_b___plugin___orders_1_1_orders_board.html", null ],
      [ "THB_Plugin_Orders.OrdersBoard", "dd/d7c/class_t_h_b___plugin___orders_1_1_orders_board.html", null ],
      [ "THB_Plugin_Orders.OrdersBoard", "dd/d7c/class_t_h_b___plugin___orders_1_1_orders_board.html", null ],
      [ "THB_Plugin_Orders.UserControl1", "d2/dc6/class_t_h_b___plugin___orders_1_1_user_control1.html", null ],
      [ "THB_Plugin_Social.Achivments.Achivments", "d8/dcc/class_t_h_b___plugin___social_1_1_achivments_1_1_achivments.html", null ],
      [ "THB_Plugin_Social.Achivments.Achivments", "d8/dcc/class_t_h_b___plugin___social_1_1_achivments_1_1_achivments.html", null ],
      [ "THB_Plugin_Social.Achivments.Achivments", "d8/dcc/class_t_h_b___plugin___social_1_1_achivments_1_1_achivments.html", null ],
      [ "THB_Plugin_Social.Achivments.Achivments", "d8/dcc/class_t_h_b___plugin___social_1_1_achivments_1_1_achivments.html", null ],
      [ "THB_Plugin_Social.Advices.Advices", "dc/d36/class_t_h_b___plugin___social_1_1_advices_1_1_advices.html", null ],
      [ "THB_Plugin_Social.Advices.Advices", "dc/d36/class_t_h_b___plugin___social_1_1_advices_1_1_advices.html", null ],
      [ "THB_Plugin_Social.Advices.Advices", "dc/d36/class_t_h_b___plugin___social_1_1_advices_1_1_advices.html", null ],
      [ "THB_Plugin_Social.Advices.Advices", "dc/d36/class_t_h_b___plugin___social_1_1_advices_1_1_advices.html", null ],
      [ "THB_Plugin_Social.PersonalStatistic.PersonalStatistic", "d7/d60/class_t_h_b___plugin___social_1_1_personal_statistic_1_1_personal_statistic.html", null ],
      [ "THB_Plugin_Social.PersonalStatistic.PersonalStatistic", "d7/d60/class_t_h_b___plugin___social_1_1_personal_statistic_1_1_personal_statistic.html", null ],
      [ "THB_Plugin_Social.PersonalStatistic.PersonalStatistic", "d7/d60/class_t_h_b___plugin___social_1_1_personal_statistic_1_1_personal_statistic.html", null ],
      [ "THB_Plugin_Social.PersonalStatistic.PersonalStatistic", "d7/d60/class_t_h_b___plugin___social_1_1_personal_statistic_1_1_personal_statistic.html", null ],
      [ "THB_Plugin_Social.UserControl1", "d1/d79/class_t_h_b___plugin___social_1_1_user_control1.html", null ],
      [ "WpfHandler.UserControl1", "dd/d5d/class_wpf_handler_1_1_user_control1.html", null ]
    ] ],
    [ "InternalTypeHelper", null, [
      [ "XamlGeneratedNamespace.GeneratedInternalTypeHelper", "dc/db0/class_xaml_generated_namespace_1_1_generated_internal_type_helper.html", null ],
      [ "XamlGeneratedNamespace.GeneratedInternalTypeHelper", "dc/db0/class_xaml_generated_namespace_1_1_generated_internal_type_helper.html", null ]
    ] ],
    [ "TeacherHandbook.Core.Orders.IOrder", "df/d8a/interface_teacher_handbook_1_1_core_1_1_orders_1_1_i_order.html", [
      [ "TeacherHandbook.Core.Orders.BaseOrder", "df/d39/class_teacher_handbook_1_1_core_1_1_orders_1_1_base_order.html", [
        [ "TeacherHandbook.Core.Orders.MentoringOrder", "d8/d91/class_teacher_handbook_1_1_core_1_1_orders_1_1_mentoring_order.html", null ]
      ] ]
    ] ],
    [ "IPlugin", null, [
      [ "THB_Plugin_Lesson.AttendanceLog", "de/d96/class_t_h_b___plugin___lesson_1_1_attendance_log.html", null ],
      [ "THB_Plugin_Orders.AddOrder", "d4/d17/class_t_h_b___plugin___orders_1_1_add_order.html", null ]
    ] ],
    [ "IPlugin", null, [
      [ "TeacherHandbook.Plugins.Feed.Feed", "d2/d56/class_teacher_handbook_1_1_plugins_1_1_feed_1_1_feed.html", null ],
      [ "TeacherHandbook.Plugins.Schedule.Schedule", "dc/d1d/class_teacher_handbook_1_1_plugins_1_1_schedule_1_1_schedule.html", null ],
      [ "THB_Plugin_Exams.ExamPlanner", "df/df8/class_t_h_b___plugin___exams_1_1_exam_planner.html", null ],
      [ "THB_Plugin_Exams.Monitor", "d9/d79/class_t_h_b___plugin___exams_1_1_monitor.html", null ],
      [ "THB_Plugin_Exams.TestConstructor", "d4/d8d/class_t_h_b___plugin___exams_1_1_test_constructor.html", null ],
      [ "THB_Plugin_Lesson.Assesments", "d7/dc2/class_t_h_b___plugin___lesson_1_1_assesments.html", null ],
      [ "THB_Plugin_Lesson.LessonBoard", "d1/d3b/class_t_h_b___plugin___lesson_1_1_lesson_board.html", null ],
      [ "THB_Plugin_Lesson.Repository", "d1/df2/class_t_h_b___plugin___lesson_1_1_repository.html", null ],
      [ "THB_Plugin_Orders.OrdersBoard", "dd/d7c/class_t_h_b___plugin___orders_1_1_orders_board.html", null ],
      [ "THB_Plugin_Social.Achivments.Achivments", "d8/dcc/class_t_h_b___plugin___social_1_1_achivments_1_1_achivments.html", null ],
      [ "THB_Plugin_Social.Advices.Advices", "dc/d36/class_t_h_b___plugin___social_1_1_advices_1_1_advices.html", null ],
      [ "THB_Plugin_Social.PersonalStatistic.PersonalStatistic", "d7/d60/class_t_h_b___plugin___social_1_1_personal_statistic_1_1_personal_statistic.html", null ]
    ] ],
    [ "IQueryHandler", null, [
      [ "THB_Data_Server_Queries.GET_DAYS_RANGE", "de/de2/class_t_h_b___data___server___queries_1_1_g_e_t___d_a_y_s___r_a_n_g_e.html", null ]
    ] ],
    [ "TeacherHandbook.Core.Containers.Entities.IUser", "d1/dfc/interface_teacher_handbook_1_1_core_1_1_containers_1_1_entities_1_1_i_user.html", [
      [ "TeacherHandbook.Core.Containers.Entities.BaseUser", "d2/dbe/class_teacher_handbook_1_1_core_1_1_containers_1_1_entities_1_1_base_user.html", [
        [ "TeacherHandbook.Core.Containers.Entities.Teacher", "d5/d63/class_teacher_handbook_1_1_core_1_1_containers_1_1_entities_1_1_teacher.html", null ]
      ] ]
    ] ],
    [ "TeacherHandbook.Core.Localization.LanguageContaier", "db/dd2/class_teacher_handbook_1_1_core_1_1_localization_1_1_language_contaier.html", null ],
    [ "TeacherHandbook.Core.Containers.Schedule.Logbook", "d5/d0e/class_teacher_handbook_1_1_core_1_1_containers_1_1_schedule_1_1_logbook.html", null ],
    [ "TeacherHandbook.Core.Containers.CrossTypes.NameContainer", "d0/d8b/class_teacher_handbook_1_1_core_1_1_containers_1_1_cross_types_1_1_name_container.html", null ],
    [ "TeacherHandbook.Core.Orders.OrderDate", "dc/d14/struct_teacher_handbook_1_1_core_1_1_orders_1_1_order_date.html", null ],
    [ "WpfHandler.Properties.Resources", "d2/d90/class_wpf_handler_1_1_properties_1_1_resources.html", null ],
    [ "THB_Plugin_Orders.Properties.Resources", "d6/d74/class_t_h_b___plugin___orders_1_1_properties_1_1_resources.html", null ],
    [ "TeacherHandbook.Properties.Resources", "de/d69/class_teacher_handbook_1_1_properties_1_1_resources.html", null ],
    [ "THB_Data_Server.Properties.Resources", "d1/d40/class_t_h_b___data___server_1_1_properties_1_1_resources.html", null ],
    [ "THB_Plugin_Exams.Properties.Resources", "d8/d18/class_t_h_b___plugin___exams_1_1_properties_1_1_resources.html", null ],
    [ "THB_Plugin_Social.Properties.Resources", "d9/df5/class_t_h_b___plugin___social_1_1_properties_1_1_resources.html", null ],
    [ "THB_Plugin_Lesson.Properties.Resources", "d1/d04/class_t_h_b___plugin___lesson_1_1_properties_1_1_resources.html", null ],
    [ "TeacherHandbook.Core.Containers.Schedule.Session", "d5/d8e/class_teacher_handbook_1_1_core_1_1_containers_1_1_schedule_1_1_session.html", null ],
    [ "TeacherHandbook.Core.Containers.Schedule.Subject", "db/dce/class_teacher_handbook_1_1_core_1_1_containers_1_1_schedule_1_1_subject.html", null ],
    [ "UserControl", null, [
      [ "TeacherHandbook.CatalogButton", "d2/d3e/class_teacher_handbook_1_1_catalog_button.html", null ],
      [ "TeacherHandbook.Controls.CatalogButton", "df/d61/class_teacher_handbook_1_1_controls_1_1_catalog_button.html", null ],
      [ "TeacherHandbook.Controls.CatalogButton", "df/d61/class_teacher_handbook_1_1_controls_1_1_catalog_button.html", null ],
      [ "TeacherHandbook.Controls.CatalogButton", "df/d61/class_teacher_handbook_1_1_controls_1_1_catalog_button.html", null ],
      [ "TeacherHandbook.Controls.CatalogButton", "df/d61/class_teacher_handbook_1_1_controls_1_1_catalog_button.html", null ],
      [ "TeacherHandbook.Controls.CatalogButton", "df/d61/class_teacher_handbook_1_1_controls_1_1_catalog_button.html", null ],
      [ "TeacherHandbook.Controls.UserControl1", "d6/dc1/class_teacher_handbook_1_1_controls_1_1_user_control1.html", null ],
      [ "TeacherHandbook.Plugins.Feed.Feed", "d2/d56/class_teacher_handbook_1_1_plugins_1_1_feed_1_1_feed.html", null ],
      [ "TeacherHandbook.Plugins.Feed.Feed", "d2/d56/class_teacher_handbook_1_1_plugins_1_1_feed_1_1_feed.html", null ],
      [ "TeacherHandbook.Plugins.Feed.Feed", "d2/d56/class_teacher_handbook_1_1_plugins_1_1_feed_1_1_feed.html", null ],
      [ "TeacherHandbook.Plugins.Feed.Feed", "d2/d56/class_teacher_handbook_1_1_plugins_1_1_feed_1_1_feed.html", null ],
      [ "TeacherHandbook.Plugins.Feed.Feed", "d2/d56/class_teacher_handbook_1_1_plugins_1_1_feed_1_1_feed.html", null ],
      [ "TeacherHandbook.Plugins.Feed.Feed", "d2/d56/class_teacher_handbook_1_1_plugins_1_1_feed_1_1_feed.html", null ],
      [ "TeacherHandbook.Plugins.Feed.Feed", "d2/d56/class_teacher_handbook_1_1_plugins_1_1_feed_1_1_feed.html", null ],
      [ "TeacherHandbook.Plugins.Feed.Feed", "d2/d56/class_teacher_handbook_1_1_plugins_1_1_feed_1_1_feed.html", null ],
      [ "TeacherHandbook.Plugins.Schedule.Schedule", "dc/d1d/class_teacher_handbook_1_1_plugins_1_1_schedule_1_1_schedule.html", null ],
      [ "TeacherHandbook.Plugins.Schedule.Schedule", "dc/d1d/class_teacher_handbook_1_1_plugins_1_1_schedule_1_1_schedule.html", null ],
      [ "TeacherHandbook.Plugins.Schedule.Schedule", "dc/d1d/class_teacher_handbook_1_1_plugins_1_1_schedule_1_1_schedule.html", null ],
      [ "TeacherHandbook.Plugins.Schedule.Schedule", "dc/d1d/class_teacher_handbook_1_1_plugins_1_1_schedule_1_1_schedule.html", null ],
      [ "TeacherHandbook.Plugins.Schedule.Schedule", "dc/d1d/class_teacher_handbook_1_1_plugins_1_1_schedule_1_1_schedule.html", null ],
      [ "TeacherHandbook.Plugins.Schedule.Schedule", "dc/d1d/class_teacher_handbook_1_1_plugins_1_1_schedule_1_1_schedule.html", null ],
      [ "THB_Plugin_Exams.ExamPlanner", "df/df8/class_t_h_b___plugin___exams_1_1_exam_planner.html", null ],
      [ "THB_Plugin_Exams.ExamPlanner", "df/df8/class_t_h_b___plugin___exams_1_1_exam_planner.html", null ],
      [ "THB_Plugin_Exams.ExamPlanner", "df/df8/class_t_h_b___plugin___exams_1_1_exam_planner.html", null ],
      [ "THB_Plugin_Exams.ExamPlanner", "df/df8/class_t_h_b___plugin___exams_1_1_exam_planner.html", null ],
      [ "THB_Plugin_Exams.ExamPlanner", "df/df8/class_t_h_b___plugin___exams_1_1_exam_planner.html", null ],
      [ "THB_Plugin_Exams.Monitor", "d9/d79/class_t_h_b___plugin___exams_1_1_monitor.html", null ],
      [ "THB_Plugin_Exams.Monitor", "d9/d79/class_t_h_b___plugin___exams_1_1_monitor.html", null ],
      [ "THB_Plugin_Exams.Monitor", "d9/d79/class_t_h_b___plugin___exams_1_1_monitor.html", null ],
      [ "THB_Plugin_Exams.Monitor", "d9/d79/class_t_h_b___plugin___exams_1_1_monitor.html", null ],
      [ "THB_Plugin_Exams.Monitor", "d9/d79/class_t_h_b___plugin___exams_1_1_monitor.html", null ],
      [ "THB_Plugin_Exams.TestConstructor", "d4/d8d/class_t_h_b___plugin___exams_1_1_test_constructor.html", null ],
      [ "THB_Plugin_Exams.TestConstructor", "d4/d8d/class_t_h_b___plugin___exams_1_1_test_constructor.html", null ],
      [ "THB_Plugin_Exams.TestConstructor", "d4/d8d/class_t_h_b___plugin___exams_1_1_test_constructor.html", null ],
      [ "THB_Plugin_Exams.TestConstructor", "d4/d8d/class_t_h_b___plugin___exams_1_1_test_constructor.html", null ],
      [ "THB_Plugin_Exams.TestConstructor", "d4/d8d/class_t_h_b___plugin___exams_1_1_test_constructor.html", null ],
      [ "THB_Plugin_Exams.UserControl1", "d4/ddd/class_t_h_b___plugin___exams_1_1_user_control1.html", null ],
      [ "THB_Plugin_Lesson.Assesments", "d7/dc2/class_t_h_b___plugin___lesson_1_1_assesments.html", null ],
      [ "THB_Plugin_Lesson.Assesments", "d7/dc2/class_t_h_b___plugin___lesson_1_1_assesments.html", null ],
      [ "THB_Plugin_Lesson.Assesments", "d7/dc2/class_t_h_b___plugin___lesson_1_1_assesments.html", null ],
      [ "THB_Plugin_Lesson.Assesments", "d7/dc2/class_t_h_b___plugin___lesson_1_1_assesments.html", null ],
      [ "THB_Plugin_Lesson.Assesments", "d7/dc2/class_t_h_b___plugin___lesson_1_1_assesments.html", null ],
      [ "THB_Plugin_Lesson.AttendanceLog", "de/d96/class_t_h_b___plugin___lesson_1_1_attendance_log.html", null ],
      [ "THB_Plugin_Lesson.AttendanceLog", "de/d96/class_t_h_b___plugin___lesson_1_1_attendance_log.html", null ],
      [ "THB_Plugin_Lesson.AttendanceLog", "de/d96/class_t_h_b___plugin___lesson_1_1_attendance_log.html", null ],
      [ "THB_Plugin_Lesson.AttendanceLog", "de/d96/class_t_h_b___plugin___lesson_1_1_attendance_log.html", null ],
      [ "THB_Plugin_Lesson.AttendanceLog", "de/d96/class_t_h_b___plugin___lesson_1_1_attendance_log.html", null ],
      [ "THB_Plugin_Lesson.LessonBoard", "d1/d3b/class_t_h_b___plugin___lesson_1_1_lesson_board.html", null ],
      [ "THB_Plugin_Lesson.LessonBoard", "d1/d3b/class_t_h_b___plugin___lesson_1_1_lesson_board.html", null ],
      [ "THB_Plugin_Lesson.LessonBoard", "d1/d3b/class_t_h_b___plugin___lesson_1_1_lesson_board.html", null ],
      [ "THB_Plugin_Lesson.LessonBoard", "d1/d3b/class_t_h_b___plugin___lesson_1_1_lesson_board.html", null ],
      [ "THB_Plugin_Lesson.LessonBoard", "d1/d3b/class_t_h_b___plugin___lesson_1_1_lesson_board.html", null ],
      [ "THB_Plugin_Lesson.LessonBoard", "d1/d3b/class_t_h_b___plugin___lesson_1_1_lesson_board.html", null ],
      [ "THB_Plugin_Lesson.Repository", "d1/df2/class_t_h_b___plugin___lesson_1_1_repository.html", null ],
      [ "THB_Plugin_Lesson.Repository", "d1/df2/class_t_h_b___plugin___lesson_1_1_repository.html", null ],
      [ "THB_Plugin_Lesson.Repository", "d1/df2/class_t_h_b___plugin___lesson_1_1_repository.html", null ],
      [ "THB_Plugin_Lesson.Repository", "d1/df2/class_t_h_b___plugin___lesson_1_1_repository.html", null ],
      [ "THB_Plugin_Lesson.Repository", "d1/df2/class_t_h_b___plugin___lesson_1_1_repository.html", null ],
      [ "THB_Plugin_Lesson.UserControl1", "d4/dec/class_t_h_b___plugin___lesson_1_1_user_control1.html", null ],
      [ "THB_Plugin_Orders.AddOrder", "d4/d17/class_t_h_b___plugin___orders_1_1_add_order.html", null ],
      [ "THB_Plugin_Orders.AddOrder", "d4/d17/class_t_h_b___plugin___orders_1_1_add_order.html", null ],
      [ "THB_Plugin_Orders.AddOrder", "d4/d17/class_t_h_b___plugin___orders_1_1_add_order.html", null ],
      [ "THB_Plugin_Orders.AddOrder", "d4/d17/class_t_h_b___plugin___orders_1_1_add_order.html", null ],
      [ "THB_Plugin_Orders.AddOrder", "d4/d17/class_t_h_b___plugin___orders_1_1_add_order.html", null ],
      [ "THB_Plugin_Orders.OrdersBoard", "dd/d7c/class_t_h_b___plugin___orders_1_1_orders_board.html", null ],
      [ "THB_Plugin_Orders.OrdersBoard", "dd/d7c/class_t_h_b___plugin___orders_1_1_orders_board.html", null ],
      [ "THB_Plugin_Orders.OrdersBoard", "dd/d7c/class_t_h_b___plugin___orders_1_1_orders_board.html", null ],
      [ "THB_Plugin_Orders.OrdersBoard", "dd/d7c/class_t_h_b___plugin___orders_1_1_orders_board.html", null ],
      [ "THB_Plugin_Orders.OrdersBoard", "dd/d7c/class_t_h_b___plugin___orders_1_1_orders_board.html", null ],
      [ "THB_Plugin_Orders.UserControl1", "d2/dc6/class_t_h_b___plugin___orders_1_1_user_control1.html", null ],
      [ "THB_Plugin_Social.Achivments.Achivments", "d8/dcc/class_t_h_b___plugin___social_1_1_achivments_1_1_achivments.html", null ],
      [ "THB_Plugin_Social.Achivments.Achivments", "d8/dcc/class_t_h_b___plugin___social_1_1_achivments_1_1_achivments.html", null ],
      [ "THB_Plugin_Social.Achivments.Achivments", "d8/dcc/class_t_h_b___plugin___social_1_1_achivments_1_1_achivments.html", null ],
      [ "THB_Plugin_Social.Achivments.Achivments", "d8/dcc/class_t_h_b___plugin___social_1_1_achivments_1_1_achivments.html", null ],
      [ "THB_Plugin_Social.Achivments.Achivments", "d8/dcc/class_t_h_b___plugin___social_1_1_achivments_1_1_achivments.html", null ],
      [ "THB_Plugin_Social.Advices.Advices", "dc/d36/class_t_h_b___plugin___social_1_1_advices_1_1_advices.html", null ],
      [ "THB_Plugin_Social.Advices.Advices", "dc/d36/class_t_h_b___plugin___social_1_1_advices_1_1_advices.html", null ],
      [ "THB_Plugin_Social.Advices.Advices", "dc/d36/class_t_h_b___plugin___social_1_1_advices_1_1_advices.html", null ],
      [ "THB_Plugin_Social.Advices.Advices", "dc/d36/class_t_h_b___plugin___social_1_1_advices_1_1_advices.html", null ],
      [ "THB_Plugin_Social.Advices.Advices", "dc/d36/class_t_h_b___plugin___social_1_1_advices_1_1_advices.html", null ],
      [ "THB_Plugin_Social.PersonalStatistic.PersonalStatistic", "d7/d60/class_t_h_b___plugin___social_1_1_personal_statistic_1_1_personal_statistic.html", null ],
      [ "THB_Plugin_Social.PersonalStatistic.PersonalStatistic", "d7/d60/class_t_h_b___plugin___social_1_1_personal_statistic_1_1_personal_statistic.html", null ],
      [ "THB_Plugin_Social.PersonalStatistic.PersonalStatistic", "d7/d60/class_t_h_b___plugin___social_1_1_personal_statistic_1_1_personal_statistic.html", null ],
      [ "THB_Plugin_Social.PersonalStatistic.PersonalStatistic", "d7/d60/class_t_h_b___plugin___social_1_1_personal_statistic_1_1_personal_statistic.html", null ],
      [ "THB_Plugin_Social.PersonalStatistic.PersonalStatistic", "d7/d60/class_t_h_b___plugin___social_1_1_personal_statistic_1_1_personal_statistic.html", null ],
      [ "THB_Plugin_Social.UserControl1", "d1/d79/class_t_h_b___plugin___social_1_1_user_control1.html", null ],
      [ "WpfHandler.UserControl1", "dd/d5d/class_wpf_handler_1_1_user_control1.html", null ]
    ] ],
    [ "TeacherHandbook.Core.Containers.Schedule.Week", "de/d25/class_teacher_handbook_1_1_core_1_1_containers_1_1_schedule_1_1_week.html", null ],
    [ "Window", null, [
      [ "TeacherHandbook.MainWindow", "df/d32/class_teacher_handbook_1_1_main_window.html", null ],
      [ "TeacherHandbook.MainWindow", "df/d32/class_teacher_handbook_1_1_main_window.html", null ],
      [ "TeacherHandbook.MainWindow", "df/d32/class_teacher_handbook_1_1_main_window.html", null ],
      [ "TeacherHandbook.MainWindow", "df/d32/class_teacher_handbook_1_1_main_window.html", null ],
      [ "TeacherHandbook.MainWindow", "df/d32/class_teacher_handbook_1_1_main_window.html", null ]
    ] ]
];